### ISSUE TITLE
Az autó R válóállásban tolat

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#10]
Tolatás megvalósítása

- [x] Az autó R sebesség állapotban tolatásba kezd.

**Comment by pintergreg** [comment]
- Mit jelent a tolatás megvalósítás?
- Mit fog csinálni az a kolléga, aki ezt a taszkot magára vállalja?
- Milyen állapotváltozással jár az, hogy az autó tolat?
