### ISSUE TITLE
Az autó a gázpedál felengedésével lassul

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#11]
Feladat: 
- Az autó lassítása a gázpedál felengedésével
- Az autót lassító erők alkalmazása

**Definition of Done:**
- [x] Az autó a lassító erők alapján lassul a gázpedál felengedésével.

**Comment by pintergreg** [comment]
Milyen ellenállások vannak? Hány ohm-osak? :wink:
