### ISSUE TITLE
Az autó gázpedál állásától függően gyorsul

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#12]
Feladatok:
- Gyorsulás megvalósítása
- Előre és hátra haladás
- Egyenletes mozgás előre/hátra
- Fontos figyelembe venni az autót fékező erőket.

**Definition of Done:** 
- [x] Az autó gázpedál állásától függűen gyorsul
- [x] Az autó előre felé gyorsul
- [x] Az autó hátrafelé gyorsul
- [x] Az autó egyenletesen mozog.

**Comment by pintergreg** [comment]
- Ha nem gyorsul, akkor egyenletesen halad előre?
- Csak előre haladhat?
- Csak előre gyorsulhat?
- Mi kell ahhoz, hogy egyenletesen haladjon előre, **ha** a #11 implementálva van?
