### ISSUE TITLE
az automata váltó 4 „fokozata” szabályozható

### ISSUE THREAD

**Issue by kibedy** [SzFMV2018-Osz/AutomatedCar-A#28]
Felhasználó állíthatja a menetirányt (D: előre, R: hátra) , illetve parkoló(P)/üres(N) fokozatba teheti a váltót. Ekkor gáz adásra nem mozdul a jármű.
PageUp/PageDown-nal lehet állítani

**Comment by pintergreg** [comment]
A jármű nem mozdul, de egyébként mi történik ha üresben gázt ad?

**Comment by kibedy** [comment]
Felpörög a fordulatszám tiltásig, vagy a gáz nyomásának megfelelő mértékig?

**Comment by pintergreg** [comment]
@kibedy Mert a gázpedál egy az egyben le van lépezve egy fordulatszámra értékre? Vagy mit jelent a  „gáz nyomásának megfelelő mérték”?
A „tiltás” lehet egy jó megoldás, mivel értelemszerűen nem pöröghet akármeddig.
Ezt szokták úgy megoldani, hogy megnéznek egy valós autó váltókarakterisztikát és fokozatokhoz (valami limitet rendelnek). Itt most nem az automata PRND állásait, hanem „belső fokozatot”, pl. 1..5 értek.
