### ISSUE TITLE
Render interface létrehozása TA2-01

### ISSUE THREAD

**Issue by uroborospit** [SzFMV2018-Osz/AutomatedCar-A#32]
Rendelkezzen egy Kép létrehozó method-al és egy RotateImage method-al.
- [x] Létezik InitImage method
- [x] Létezik  RotateImage method

**Comment by uroborospit** [comment]
@ral2bp A képek referencia pontja valahol számos formában is megtalálható csak mert az hogy van egy lista és a képeken egy piros pötty nem segít túl sokat.

**Comment by pintergreg** [comment]
@uroborospit Nincs még összegyűjtve. Folyamatosan tervben van, de nem jutottam még el oda. Egyik opció, hogy megnézed egy képszerkesztőben, hogy melyik pixel legyen, másik, hogy megnézed, hogy mások korábban minek választották meg azt a pontot.
