### ISSUE TITLE
Autó követő kamera TA2-05

### ISSUE THREAD

**Issue by Ryaqu** [SzFMV2018-Osz/AutomatedCar-A#33]
Autó kamera beállítása a WordObject ősosztályból származó X és Y koordináták (számolva az autó nagyságát) alapján meghatározása.

- [x] Autó középen helyezkedik el  
- [x] Kamera követi a tényleges autót
- [x] Kamera nem mehet ki a pályából, de ilyenkor az autó kimehet a kamerából

**Comment by Ryaqu** [comment]
Autó középen elhelyezkedéssel, annyi probléma van, hogy jelenleg egy az általam meghatározott számot használ a kocsi nagyságára (szóval ehhez szükséges lenne egy AutomatedCar width-re, height-re)

**Comment by pintergreg** [comment]
@Ryaqu Ha ezt nem te akarod implementálni, akkor célszerű lehet belinkelni azt az egyént vagy csapatot akitől ennek megvalósítását várod. Sőt, ha másik csapat, célszerű lehet nekik issue-t felvinni (ennek nincs jogosultság szintű korlátja). Azt az issue-t meg ide lehet linkelni.

**Comment by Ryaqu** [comment]
Commitoltam a megoldásom. Jelenleg ez jónak tűnik.
