### ISSUE TITLE
Translation Matrix létrehozása a renderhez TA2-04

### ISSUE THREAD

**Issue by uroborospit** [SzFMV2018-Osz/AutomatedCar-A#37]

**Comment by pintergreg** [comment]
- Mi az, hogy translation matrix?
- Miből lesz létrehozva?
- Mi lesz osztály szinten a kimenet?

**Comment by uroborospit** [comment]
Ez a kamera kezelés alapjául szolgáló mátrix lett volna de mivel csoport társam addigra elkezdte a kamerát ez az issue törölve lett mivel a másik issue magába foglalja

**Comment by uroborospit** [comment]
Csak elfelejtetten lezárni az elvetett issue-t elnézés
