### ISSUE TITLE
a fék állapota változik gombnyomásra

### ISSUE THREAD

**Issue by Norberg95** [SzFMV2018-Osz/AutomatedCar-A#38]
- [x] A gombnyomás időtartamának függvényében növekszik a fékhatás, amíg az el nem éri a maximális értéket. 

- [x] A gomb felengedése utáni eltelt idő függvényében csökken a fékhatás, amíg az meg nem szűnik.

- [x] A fékhatás 0-100 skálán mozog.

**Comment by pintergreg** [comment]
Itt minden sor lehetne egy DoD pont, aztán ki kellene fejteni, hogy miképpen kell ezt megoldani.
