### ISSUE TITLE
Irányjelző visszajelző megjelenítése

### ISSUE THREAD

**Issue by hege-93** [SzFMV2018-Osz/AutomatedCar-A#50]
Irányjelző visszajelző megjelenítése két nyíl (balra, jobbra). Indexelés esetén a megfelelőnyíl színének megváltoztatása.

**Comment by pintergreg** [comment]
@hege-93 Csak úgy mint a többi issue-dnál leírtad a DoD-t (bár szintaktikailag nem), de lehetne még tovább részletezni implementáció szinten: honnan veszed az adatot, stb. Ez itt ezeknél az egyszerű taszkoknál túlzásnak tűnhet, de az issue akár (fejlesztői) dokumentáció is lehet.

Felelőse és határideje azonban így sincs.

**Comment by kibedy** [comment]
Az irányjelző kapcsolható és megjeleníthező részt megcsináltam. Ta3_27_iranyjelzo branch-ban benne van.
