### ISSUE TITLE
Mozgásvektor meghatározása 

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#7]
Feladat:
Tényleges mozgásvektor meghatározása a motor csapat gyorsulás, lassulás értékének felhasználásával

**Definition of Done:**
- [x] gyorsulás/lassulás értékek lekérése
- [x] új sebesség számítás
- [x] új koordináták kiszámítása (sinus, cosinus)

**Comment by pintergreg** [comment]
Egy taszknak van egy rövid tömör címe/tárgya és egy törzse, kb. mint egy e-mailnek. A tárgy nem a törzs, a törzs meg nem a tárgy!
