### ISSUE TITLE
Az autó pozíciójának frissítése

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#8]
A meghatározott mozgásvektor alapján az autó pozíciójának frissítése

**Comment by pintergreg** [comment]
- Hogy néz ki a mozgásvektor?
- Milyen osztály reprezentálja?
- Ezt ki implementál[ja|ta]?
- Minden csapat tudja, hogy ez hogy működik?
    - Főképpen az a csapat, akitől ezt várjátok...
- Hogyan néz ki a pozíció frissítése?
