### ISSUE TITLE
collidable Interface megvalósítása TA2-07

### ISSUE THREAD

**Issue by uroborospit** [SzFMV2018-Osz/AutomatedCar-A#84]
Meg kell tervezni a ICollidable interface-t.

- [x] Létezik az Interface

**Comment by uroborospit** [comment]
Meg kell tervezni a ICollidable interface-t.

Egy lehetséges megvalósítás az hogy tartalmaz egy darab logikai függvényt amelynek be kell adni egy oibjektumot ami rendelkezik az ICollidable interface-el és ez a függvényt vissza adja hogy van-e ütközés.

- [ ] Létezik az Interface

**Comment by uroborospit** [comment]
@SzFMV2018-Osz/team-a1  Az adatmodellek kapcsán szeretnénk veletek valamikor konzultálni továbbá hogy implementálhassuk a ti XML betöltőtöket. Kérnék Legalább 2 időpontot amikor egy képben lévő tagotok rá érne konzultálni hogy megvalósítsuk a változásokat.

**Comment by uroborospit** [comment]
@RPeter7  ma 17:30-22:00 holnap 16:30-19:00 esetleg még vasárnap de részemről jobb lenne ma holnap. Kérlek jelezz vissza hogy mikor hogy ne tervezzek oda semmit köszönöm.

**Comment by RPeter7** [comment]
@uroborospit Valószínűleg velem fogsz beszélni, szóval azt mondom ,hogy nekem a mai nap lenne jó. Igaz nem vagyok otthon, a városban leszek, de leülök majd valahova és akkor tudunk akár szóban is beszélni, ha neked így megfelel.

**Comment by uroborospit** [comment]
@RPeter7  Nekem megfelel. Mikor lenne jó?

**Comment by RPeter7** [comment]
@uroborospit Na ez egy jó kérdés. 6-8 -ig tartó intervallumban. De lehetséges, hogy 8-9 között haza érek, akkor viszont 10-ig beszélhetünk! Fontos, hogy megmondjam, pontosan mikor tudunk beszélni?

**Comment by uroborospit** [comment]
@RPeter7  amennyiben neked nem gond ha jelentkezés után esetleg egy 10-15 percet még várni kell rám nem, csak addig én is mással foglalkozom és nem biztos hogy azonnal tudok reagálni

**Comment by uroborospit** [comment]
@RPeter7  Rendben Bakay Attila néven megtalálsz

**Comment by uroborospit** [comment]
A1 megvalósította az előző sprintben így lezártnak tekintem.
