### ISSUE TITLE
Autó kanyarodásának biztosítása valóságos fordulókör szerint

### ISSUE THREAD

**Issue by galbavi** [SzFMV2018-Osz/AutomatedCar-A#9]
**Definition of Done:**
- [x] autó osztály létrehozása
- [x] autó szélességének és tengelytávjának kiszámolása
- [x] fordulókör kiszámolása képlet szerint

**Comment by ravaszla** [comment]
Nincs definition of done  - pár pontban fel kéne jegyezni, mikor is van kész ez a task.

Pl. - autó balra gombra balra fordul, jobbra gombra jobbra fordul, a fordulókör nagysága függ a sebességtől, az autó nem "úszik", a fordulás valósághoz közeli látvány, hasonlók. Van benne szubjektív, de érdemes legalább a csapat szintjén eldöntendő, pipálható elemeket felvenni.
